apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: http-servicemonitor
  labels:
    release: promstack
spec:
  # namespaceSelector:
  #   any: true
  namespaceSelector:
    matchNames:
    - kong
  selector:
    matchLabels:
      app: http-svc
      enable-metrics: "true"
  endpoints:
  - port: http