version: "3"
services:
  ciao:
    image: brotandgames/ciao
    container_name: ciao
    ports:
      - '8090:3000'
    environment:
      - SECRET_KEY_BASE=random
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=admin
      - PROMETHEUS_ENABLED=true
      - PROMETHEUS_BASIC_AUTH_USERNAME=admin
      - PROMETHEUS_BASIC_AUTH_PASSWORD=admin
      - CIAO_LOG_LEVEL=INFO
      - CIAO_WEBHOOK_ENDPOINT_SLACK1=https://hooks.slack.com/services/< Update with webhook >
      - 'CIAO_WEBHOOK_PAYLOAD_SLACK1={"text":"[ciao] __name__: Status changed (__status_after__)"}'


    volumes:
      - /opt/ciao/data:/app/db/sqlite/
