apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: comments
  labels:
    release: kong-dp
spec:
  namespaceSelector:
    any: true
  endpoints:
  - port: http
  selector:
    matchLabels:
      app: comments
