# https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/monitoring-additional-namespaces.md#defining-the-servicemonitor-for-each-additional-namespace

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: httpbin
  labels:
    release: promstack
spec:
  selector:
    matchLabels:
      app: httpbin
  endpoints:
  - port: http